### PR TITLE
Fix scrollbar bug in example.js

### PR DESCRIPTION
**Pull request by abhinav-anshul**
Fixed scrollbar bug

### CODE REVIEW

**Comment by siddharthkp** [comment]
Looks good!

**Comment by abhinav-anshul** [comment]
Yes, only the best practices, for example, `props` to `(props)`, brackets are not required when passing an only single parameter, however, it provides flexibility for future use cases.

In a few lines, there is only the addition of "commas".

Hence not big changes except for `auto` of course!

**Comment by abhinav-anshul** [comment]
However, If you would like me to open a new pull request targeting only `auto` I can do that :)

**Comment by abhinav-anshul** [comment]
> Fix looks good, but there are a bunch of aesthetic changes in this PR along with the fix 😅
> 
> I'm guessing those come from your editor config for prettier?

Yes that's true

**Comment by siddharthkp** [comment]
best practices around code aesthetic are silly, I'd stick to the package's prettier config

**Pull request merged**
