### PR TITLE
Fix #87 Removed hardcoded ThemeProvider for theme consistancy across pages

### LINKED ISSUE #87: Issue with theme change while redirecting to different page
- **Steps to reproduce:**

1.  visit the site `https://react-ui.dev/`
2. Change the theme from `Light to Dark`
3. then visit any of these links from `Start here:` section
Capture

> You will notice theme change after we are redirected.

- **Expected Behaviour**

`Theme should not change unless and until the user changes it manually. It should be set globally.`

### PR DESCRIPTION
**Pull request by ankibalyan**

### CODE REVIEW

**Comment by siddharthkp** [comment]
It is intentional on some pages to help with the examples below :)

**Comment by ankibalyan** [comment]
whoops!

**Comment by siddharthkp** [comment]
We can make them consistent after this PR: https://github.com/siddharthkp/react-ui/pull/77

**Comment by ankibalyan** [comment]
cool, I'm closing this.

**Pull request closed without merging**
