### PR TITLE
add forwardRef to all components

### PR DESCRIPTION
**Pull request by rubenmoya**
This PR adds `forwardRef` to all react-ui components (and ecosystem), I also took advantage of this PR and added a named function so in development the components show the name in the React Devtools.

Closes https://github.com/siddharthkp/react-ui/issues/29 and https://github.com/siddharthkp/react-ui/issues/34

### CODE REVIEW

**Comment by siddharthkp** [comment]
> not sure if we should add this to all components

I was just thinking about that 🙃 I think so.

One way to avoid that would be to use a different prop like `innerRef` which only `Element understands`, but that sounds like extra API surface to discover 🤔 

What's the standard practice here? Do folks literally wrap each component with forwardRef?

**Comment by rubenmoya** [comment]
> I was just thinking about that 🙃 I think so.
You mean all components need it right?

> What's the standard practice here? Do folks literally wrap each component with forwardRef?

That's what I've seen so far, that what ReachUI does for example

**Comment by siddharthkp** [comment]
If it's good enough for Reach, it's good enough for me 😅

**Comment by NateRadebaugh** [comment]
Hey @siddharthkp and @rubenmoya is this change ready to be merged? I'd like to add some 3rd party examples for #41  but reach-ui for example requires this PR first.

**Pull request merged**
