### PR TITLE
Fixes Stack specificity issues

### LINKED ISSUE #40: Fix Stack specificity issues
When you put elements in a Stack with gap, the gap overrides the margins on individual elements because it has higher specificity. (example in codesandbox link below)

But, if we use the [lobotomized owl selector](https://css-tricks.com/spacing-the-bottom-of-modules/), we can solve this! 

I had completely forgot about the lobotomized owl, that article ⬆️ is from 2013! and was reminded of it [from a tweet](https://twitter.com/adamwathan/status/1250583225757569027) by @adamwathan! cheers to him!

Repro and suggested fix (Stack 2): https://codesandbox.io/s/infallible-proskuriakova-5zwzg

### PR DESCRIPTION
**Pull request by Sagarpreet**
Fixes #40 

Referred this cool article: https://alistapart.com/article/axiomatic-css-and-lobotomized-owls/

### CODE REVIEW

**Comment by Sagarpreet** [comment]
Seems like Lobotomized Owls is breaking css somewhere, checking

**Comment by Sagarpreet** [comment]
Screenshot 2020-04-26 at 8 05 33 PM

**Comment by shubh0107** [comment]
This is because all examples are inside the `Example.Preview` component.
```jsx
<Example.Preview direction="vertical" gap={10}>
  <Stack justify="flex-start" gap={2}>
    ....
  </Stack>

  <Stack justify="space-between">
    ....
  </Stack>

  <Stack justify="flex-end" gap={2}>
    ....
  </Stack>
</Example.Preview>
```
And the `Preview` component is defined as a **Stack** --
```javascript
const Preview = ({ css = {}, ...props }) => {
  return (
    <Element
      as={Stack}
      css={{
        paddingY: 10,
        paddingX: 6,
        border: '1px solid',
        borderColor: 'App.borderColor',
        ...css
      }}
      {...props}
    >
      {props.children}
    </Element>
  )
}
```

Changing the selector to lobotomized owl will apply those styles to any 2 consecutive elements in a Stack. So the spacing between each example in the `Example.Preview` component will get `marginBottom: 0;`.

**Comment by siddharthkp** [comment]
@shubh0107 The preview component uses the same stack :)

I don't think this PR is working:

Screenshot 2020-05-02 at 5 52 13 PM

**Comment by shubh0107** [comment]
Right @siddharthkp .
However, i was trying to play with the codesandbox example and also the code and noticed something strange.
In the codesandbox example the `gap` on the `Stack` overrides the `marginLeft` prop on `Avatar`. However, `marginRight` works fine.

Screenshot (5)


Moreover, both `marginRight` and `marginLeft` work fine on the first `Avatar` element.

Screenshot (9)

Screenshot (10)

Is this also because of the specificity ?

**Comment by siddharthkp** [comment]
Ah, they should all work! I think I used the wrong example and concluded it works too soon 😅

still open for exploration then

**Comment by siddharthkp** [comment]
Was able to fix in https://github.com/siddharthkp/react-ui/pull/84, needed to make some root changes first https://github.com/siddharthkp/react-ui/pull/81

**Pull request closed without merging**
